# Generated by Django 3.0.6 on 2020-05-22 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('date_de_création', models.DateTimeField(auto_now_add=True)),
                ('date_de_publication', models.DateTimeField(auto_now=True)),
                ('accroche', models.CharField(default=True, max_length=200)),
                ('texte', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
