# Generated by Django 3.0.5 on 2020-05-23 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('supprimer_post', 'description supprimer un post'),)},
        ),
    ]
