# Generated by Django 3.0.5 on 2020-05-23 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200523_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('supprimer_post', 'description supprimer un post'), ('dashboard_admin', 'accès django administrateur'))},
        ),
    ]
