# Generated by Django 3.0.5 on 2020-05-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_accroche'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='accroche',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
