# Generated by Django 3.0.6 on 2020-06-12 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200612_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': (('ajouter_comment', 'ajouter un commentaire'), ('modifier_comment', 'modifier un commentaire'))},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('supprimer_post', 'description supprimer un post'), ('dashboard_admin', 'accès django administrateur'), ('modifier_post', 'modifier un post'), ('ajouter_post', 'ajouter un post'))},
        ),
    ]
