# Generated by Django 3.0.6 on 2020-06-12 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200612_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': (('ajouter_comment', 'ajouter un commentaire'),)},
        ),
    ]
