# Generated by Django 3.0.6 on 2020-06-12 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200612_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('supprimer_post', 'description supprimer un post'), ('dashboard_admin', 'accès django administrateur'), ('modifier_post', 'modifier un post'), ('ajouter_post', 'ajouter un post'), ('ajouter_comment', 'ajouter un commentaire'))},
        ),
    ]
